- hosts: local
# use priviledge (default : root)
  become: yes
# the way to use priviledge
  become_method: sudo
# define tasks
  tasks:
  - name: httpd is installed
    yum: name=httpd state=installed
  - name: httpd is running and enabled
    service: name=httpd state=started enabled=yes
